version: '2.1'
services:
    mongo:
        container_name: mongo
        image: mongo:3.2
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "root"
            MONGO_INITDB_DATABASE: yapi
        volumes:
            - ./yapi-data:/data/db
            - ./mongo-init:/docker-entrypoint-initdb.d

    yapi:
        container_name: yapi
        image: yapi
        depends_on:
            - mongo
        ports:
            - "3000:3000"
        volumes:
            - ./yapi/config.json:/api/config.json